import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";

type User = { id: string; username: string; role: "admin" | "user"; balance: number; totalTopup?: number; totalUsed?: number };
type Service = { id: string; sourceKey?: string; provider?: string; providerId?: string | number; originalName: string; name: string; providerCost: number; price: number; hidden: boolean; note?: string };
type Order = { id: string; userId?: string; appName: string; number: string; price: number; status: string; code?: string; sms?: string; createdAt: string; provider?: string; carrier?: string; refunded?: boolean };
type Topup = { id: string; userId: string; username: string; amount: number; note?: string; status: string; createdAt: string };
type Settings = { siteName: string; logoText: string; logoImage: string; background: string; announcement: string; bannerImage: string; bankName: string; bankAccountNumber: string; bankBeneficiary: string; bankQrUrl: string; topupNote: string };
type ProviderSettings = { chayEnabled: boolean; chayApiKeyMasked: string; hasChayApiKey: boolean; codesimEnabled: boolean; codesimApiKeyMasked: string; hasCodesimApiKey: boolean };

type Tab = "services" | "orders" | "topup" | "adminTopups" | "users" | "adminServices" | "api" | "settings";

const defaultSettings: Settings = { siteName: "OTP 24H", logoText: "OTP", logoImage: "", background: "bg-slate-950", announcement: "", bannerImage: "", bankName: "TECHCOMBANK", bankAccountNumber: "MS00T07014613285196", bankBeneficiary: "NGUYEN VAN HUNG", bankQrUrl: "", topupNote: "Nội dung chuyển khoản: username của bạn.\nSau khi chuyển khoản hãy tạo yêu cầu nạp tiền để admin duyệt." };
const defaultProviderSettings: ProviderSettings = { chayEnabled: true, chayApiKeyMasked: "", hasChayApiKey: false, codesimEnabled: true, codesimApiKeyMasked: "", hasCodesimApiKey: false };
const carriers = [{ label: "Tất cả nhà mạng", value: "" }, { label: "Viettel", value: "Viettel" }, { label: "Mobi", value: "Mobi" }, { label: "Vina", value: "Vina" }, { label: "VNMB", value: "VNMB" }, { label: "ITelecom", value: "ITelecom" }];
const tabLabels: Record<Tab, string> = { services: "Dịch vụ", orders: "Đơn thuê", topup: "Nạp tiền", adminTopups: "Duyệt nạp", users: "Người dùng", adminServices: "Quản lý dịch vụ", api: "API", settings: "Cài đặt" };
const money = (n: number) => Number(n || 0).toLocaleString("vi-VN") + "đ";
const sleep = (ms: number) => new Promise(r => window.setTimeout(r, ms));
function getSavedUser() { try { const raw = localStorage.getItem("otp24h_user"); return raw ? JSON.parse(raw) as User : null; } catch { return null; } }
async function apiFetch<T>(url: string, options: RequestInit = {}, timeoutMs = 40000): Promise<T> {
  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...options, signal: controller.signal });
    const text = await res.text();
    const data = text ? JSON.parse(text) : {};
    if (!res.ok) throw new Error(data?.message || "Có lỗi xảy ra");
    return data as T;
  } catch (error: any) {
    if (error?.name === "AbortError") throw new Error("Server phản hồi quá lâu, vui lòng thử lại");
    throw error;
  } finally { window.clearTimeout(timer); }
}

export default function App() {
  const [user, setUserState] = useState<User | null>(() => getSavedUser());
  const [users, setUsers] = useState<User[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [adminServices, setAdminServices] = useState<Service[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [topups, setTopups] = useState<Topup[]>([]);
  const [settings, setSettings] = useState<Settings>(defaultSettings);
  const [tab, setTab] = useState<Tab>("services");
  const [isLogin, setIsLogin] = useState(true);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const [adminServiceSearch, setAdminServiceSearch] = useState("");
  const [selectedCarrier, setSelectedCarrier] = useState("");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false);
  const [topupAmount, setTopupAmount] = useState("");
  const [topupNote, setTopupNote] = useState("");
  const [providerCounts, setProviderCounts] = useState<any>({});
  const [providerSettings, setProviderSettings] = useState<ProviderSettings>(defaultProviderSettings);
  const [chayApiKey, setChayApiKey] = useState("");
  const [codesimApiKey, setCodesimApiKey] = useState("");
  const [providerTest, setProviderTest] = useState<any>(null);
  const toastTimer = useRef<number | null>(null);
  const checkingRef = useRef(false);
  const isAdmin = user?.role === "admin";
  const setUser = useCallback((next: User | null) => { setUserState(next); next ? localStorage.setItem("otp24h_user", JSON.stringify(next)) : localStorage.removeItem("otp24h_user"); }, []);
  const headers = useMemo(() => { const h: Record<string, string> = { "Content-Type": "application/json" }; if (user?.id) h["x-user-id"] = user.id; return h; }, [user?.id]);
  const show = useCallback((msg: string) => { setNotice(msg); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = window.setTimeout(() => setNotice(""), 3500); }, []);

  const loadSettings = useCallback(async () => setSettings({ ...defaultSettings, ...(await apiFetch<Settings>("/api/settings", {}, 15000)) }), []);
  const loadServices = useCallback(async () => setServices(await apiFetch<Service[]>("/api/services", {}, 40000)), []);
  const loadOrders = useCallback(async () => { if (!user) return []; const data = await apiFetch<Order[]>(`/api/orders?userId=${encodeURIComponent(user.id)}`, {}, 20000); setOrders(data); return data; }, [user]);
  const loadTopups = useCallback(async () => { if (!user) return; setTopups(await apiFetch<Topup[]>(`/api/topups?userId=${encodeURIComponent(user.id)}`, {}, 20000)); }, [user]);
  const loadUsers = useCallback(async () => { if (!isAdmin) return; setUsers(await apiFetch<User[]>("/api/user-stats", { headers }, 20000)); }, [headers, isAdmin]);
  const loadAdminServices = useCallback(async (force = false) => { if (!isAdmin) return; const data = await apiFetch<any>(`/api/admin/services${force ? "?force=1" : ""}`, { headers }, 50000); setAdminServices(data.sources || []); setProviderCounts(data.counts || {}); }, [headers, isAdmin]);
  const loadProviderSettings = useCallback(async () => { if (!isAdmin) return; setProviderSettings({ ...defaultProviderSettings, ...(await apiFetch<ProviderSettings>("/api/admin/provider-settings", { headers }, 20000)) }); }, [headers, isAdmin]);
  const refreshCurrentTab = useCallback(async () => { if (!user) return; setLoading(true); try { if (tab === "services") await loadServices(); if (tab === "orders") await loadOrders(); if (tab === "topup" || tab === "adminTopups") await loadTopups(); if (tab === "users") await loadUsers(); if (tab === "adminServices") await loadAdminServices(); if (tab === "api") await loadProviderSettings(); } catch (e: any) { show(e.message || "Không tải được dữ liệu"); } finally { setLoading(false); } }, [user, tab, loadServices, loadOrders, loadTopups, loadUsers, loadAdminServices, loadProviderSettings, show]);

  useEffect(() => { Promise.allSettled([loadSettings(), loadServices()]); }, [loadSettings, loadServices]);
  useEffect(() => { if (!user) return; setLoading(true); Promise.allSettled([loadOrders(), loadTopups(), ...(isAdmin ? [loadUsers(), loadAdminServices(), loadProviderSettings()] : [])]).finally(() => setLoading(false)); }, [user, isAdmin, loadOrders, loadTopups, loadUsers, loadAdminServices, loadProviderSettings]);
  useEffect(() => { if (!user) return; const timer = window.setInterval(async () => { if (checkingRef.current || document.hidden) return; const waiting = orders.filter(o => o.status === "waiting").slice(0, 5); if (!waiting.length) return; checkingRef.current = true; try { await Promise.allSettled(waiting.map(o => apiFetch(`/api/orders/${o.id}/check-code`, { method: "POST", headers }, 20000))); await loadOrders(); } finally { checkingRef.current = false; } }, 7000); return () => clearInterval(timer); }, [user, orders, headers, loadOrders]);

  const login = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); try { const data = await apiFetch<User>("/api/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: username.trim(), password }) }, 20000); setUser(data); show("Đăng nhập thành công"); } catch (e: any) { show(e.message || "Đăng nhập thất bại"); } finally { setBusy(false); } };
  const register = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); try { await apiFetch("/api/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: username.trim(), password }) }, 20000); show("Đăng ký thành công, hãy đăng nhập"); setIsLogin(true); } catch (e: any) { show(e.message || "Đăng ký thất bại"); } finally { setBusy(false); } };
  const rentNumber = async (s: Service) => { if (!user || busy) return; if (!confirm(`Thuê ${s.name} giá ${money(s.price)}?`)) return; setBusy(true); try { const data = await apiFetch<{ order: Order; user: User }>("/api/orders", { method: "POST", headers, body: JSON.stringify({ userId: user.id, appId: s.sourceKey || s.id, carrier: selectedCarrier }) }, 50000); if (data.user) setUser(data.user); await loadOrders(); setTab("orders"); show("Đã lấy số thành công"); } catch (e: any) { show(e.message || "Không lấy được số"); } finally { setBusy(false); } };
  const checkCode = async (o: Order) => { setBusy(true); try { const data = await apiFetch<any>(`/api/orders/${o.id}/check-code`, { method: "POST", headers }, 30000); if (data.user) setUser(data.user); await loadOrders(); show(data.order?.code ? "Đã có OTP" : (data.api?.Msg || data.api?.message || "Đang chờ OTP")); } catch (e: any) { show(e.message || "Không check được code"); } finally { setBusy(false); } };
  const cancelOrder = async (o: Order) => { if (!confirm(`Hủy số ${o.number}?`)) return; setBusy(true); try { const data = await apiFetch<any>(`/api/orders/${o.id}/cancel`, { method: "POST", headers }, 30000); if (data.user) setUser(data.user); await loadOrders(); show("Đã hủy/hoàn tiền nếu API cho phép"); } catch (e: any) { show(e.message || "Không hủy được"); } finally { setBusy(false); } };
  const saveService = async (s: Service, patch: Partial<Service>) => { await apiFetch(`/api/admin/services/${encodeURIComponent(s.sourceKey || s.id)}`, { method: "PUT", headers, body: JSON.stringify(patch) }, 20000); await Promise.allSettled([loadAdminServices(), loadServices()]); show("Đã lưu dịch vụ"); };
  const bulkSetHidden = async (hidden: boolean, onlyFiltered = false) => { const list = onlyFiltered ? filteredAdminServices : adminServices; if (!confirm(`${hidden ? "Ẩn" : "Hiện"} ${list.length} dịch vụ?`)) return; setBusy(true); try { for (let i = 0; i < list.length; i += 10) { await Promise.allSettled(list.slice(i, i + 10).map(s => apiFetch(`/api/admin/services/${encodeURIComponent(s.sourceKey || s.id)}`, { method: "PUT", headers, body: JSON.stringify({ hidden }) }, 20000))); await sleep(100); } await Promise.allSettled([loadAdminServices(), loadServices()]); show("Đã cập nhật dịch vụ"); } finally { setBusy(false); } };
  const saveProviderSettings = async () => { setBusy(true); try { const data = await apiFetch<ProviderSettings>("/api/admin/provider-settings", { method: "PUT", headers, body: JSON.stringify({ chayEnabled: providerSettings.chayEnabled, chayApiKey, codesimEnabled: providerSettings.codesimEnabled, codesimApiKey }) }, 30000); setProviderSettings(data); setChayApiKey(""); setCodesimApiKey(""); await Promise.allSettled([loadAdminServices(true), loadServices()]); show("Đã lưu cấu hình API"); } catch (e: any) { show(e.message || "Lỗi lưu API key"); } finally { setBusy(false); } };
  const testProvider = async () => { try { const data = await apiFetch<any>("/api/admin/provider-test", { headers }, 60000); setProviderTest(data); show(data.ok ? "Cả 2 API hoạt động" : "Có API đang lỗi, xem kết quả bên dưới"); } catch (e: any) { show(e.message || "Không test được API"); } };
  const changeOwnPassword = async () => { if (!user) return; const oldPassword = prompt("Nhập mật khẩu cũ"); const newPassword = prompt("Nhập mật khẩu mới"); if (!oldPassword || !newPassword) return; try { await apiFetch("/api/change-password", { method: "POST", headers, body: JSON.stringify({ userId: user.id, oldPassword, newPassword }) }); show("Đã đổi mật khẩu"); } catch (e: any) { show(e.message || "Lỗi đổi mật khẩu"); } };
  const createTopup = async () => { if (!user) return; const amount = Number(topupAmount || 0); if (!amount || amount <= 0) return show("Nhập số tiền nạp hợp lệ"); setBusy(true); try { await apiFetch("/api/topups", { method: "POST", headers, body: JSON.stringify({ userId: user.id, amount, note: topupNote }) }); setTopupAmount(""); setTopupNote(""); await loadTopups(); show("Đã gửi yêu cầu nạp tiền"); } catch (e: any) { show(e.message || "Lỗi tạo yêu cầu nạp"); } finally { setBusy(false); } };
  const approveTopup = async (t: Topup) => { await apiFetch(`/api/topups/${t.id}/approve`, { method: "POST", headers }); await Promise.allSettled([loadTopups(), loadUsers()]); show("Đã cộng tiền"); };
  const rejectTopup = async (t: Topup) => { const reason = prompt("Lý do từ chối", "") || ""; await apiFetch(`/api/topups/${t.id}/reject`, { method: "POST", headers, body: JSON.stringify({ reason }) }); await loadTopups(); show("Đã từ chối"); };
  const adjustBalance = async (u: User) => { const amount = prompt(`Nhập số tiền cộng/trừ cho ${u.username}`); if (!amount) return; await apiFetch(`/api/users/${u.id}/adjust-balance`, { method: "POST", headers, body: JSON.stringify({ amount: Number(amount) }) }); await loadUsers(); show("Đã cập nhật số dư"); };
  const changeUserPass = async (u: User) => { const p = prompt(`Mật khẩu mới cho ${u.username}`); if (!p) return; await apiFetch(`/api/users/${u.id}`, { method: "PUT", headers, body: JSON.stringify({ password: p }) }); show("Đã đổi mật khẩu"); };
  const deleteUser = async (u: User) => { if (!confirm(`Xóa user ${u.username}?`)) return; await apiFetch(`/api/users/${u.id}`, { method: "DELETE", headers }); await loadUsers(); show("Đã xóa user"); };
  const saveSettings = async () => { await apiFetch("/api/settings", { method: "PUT", headers, body: JSON.stringify(settings) }); show("Đã lưu cài đặt"); };

  const filteredServices = useMemo(() => services.filter(s => `${s.name} ${s.provider || ""}`.toLowerCase().includes(search.toLowerCase())), [services, search]);
  const filteredAdminServices = useMemo(() => adminServices.filter(s => `${s.originalName} ${s.name} ${s.id} ${s.provider || ""} ${s.providerId || ""}`.toLowerCase().includes(adminServiceSearch.toLowerCase())), [adminServices, adminServiceSearch]);

  if (!user) return <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4 text-slate-900">{notice && <Toast text={notice} />}<form onSubmit={isLogin ? login : register} className="bg-white rounded-3xl shadow-xl p-8 w-full max-w-md"><div className="flex items-center gap-3 mb-6"><Logo settings={settings} /><div><h1 className="text-3xl font-black">{settings.siteName}</h1><p className="text-slate-500">{isLogin ? "Đăng nhập tài khoản" : "Tạo tài khoản mới"}</p></div></div><input value={username} onChange={e => setUsername(e.target.value)} className="input" placeholder="Tài khoản" /><input value={password} onChange={e => setPassword(e.target.value)} type="password" className="input" placeholder="Mật khẩu" /><button className="btn w-full" disabled={busy}>{busy ? "Đang xử lý..." : isLogin ? "ĐĂNG NHẬP" : "ĐĂNG KÝ"}</button><button type="button" onClick={() => setIsLogin(!isLogin)} className="mt-5 w-full text-indigo-600 font-bold">{isLogin ? "Chưa có tài khoản? Đăng ký" : "Đã có tài khoản? Đăng nhập"}</button><p className="text-xs text-slate-400 mt-4 text-center">Admin mặc định: admin / azhung12</p></form></div>;

  const tabs: Tab[] = ["services", "orders", "topup", ...(isAdmin ? ["adminTopups", "users", "adminServices", "api", "settings"] as Tab[] : [])];
  return <div className="min-h-screen bg-slate-950 text-slate-900"><style>{`.input{width:100%;border:1px solid #e5e7eb;border-radius:1rem;padding:1rem 1.25rem;margin-bottom:1rem}.btn{background:#4f46e5;color:white;border-radius:1rem;padding:.9rem 1.2rem;font-weight:900}.btn2{background:#0f172a;color:white;border-radius:1rem;padding:.75rem 1rem;font-weight:800}.card{background:white;border-radius:1.5rem;padding:1.25rem;box-shadow:0 10px 30px rgba(15,23,42,.08)}`}</style>{notice && <Toast text={notice} />}<div className="max-w-7xl mx-auto grid md:grid-cols-[260px_1fr] gap-5 p-4"><aside className="text-white"><div className="flex items-center gap-3 mb-4"><Logo settings={settings} /><div><h2 className="text-xl font-black">{settings.siteName}</h2><p className="text-slate-300">{user.username}</p></div></div><div className="bg-slate-800 rounded-2xl p-4 mb-4"><p className="text-slate-300">Số dư</p><p className="text-2xl font-black">{money(user.balance)}</p></div><div className="space-y-2">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={`w-full text-left rounded-xl px-4 py-3 font-bold ${tab === t ? "bg-indigo-600" : "bg-slate-800"}`}>{tabLabels[t]}</button>)}</div><button onClick={changeOwnPassword} className="mt-6 bg-slate-800 rounded-xl px-4 py-3 font-bold">Đổi mật khẩu</button><button onClick={() => setUser(null)} className="mt-3 ml-2 bg-rose-600 rounded-xl px-4 py-3 font-bold">Đăng xuất</button></aside><main><div className="bg-white rounded-3xl p-5 md:p-8 min-h-[85vh]"><div className="flex items-center justify-between mb-6"><h1 className="text-3xl font-black">{tabLabels[tab]}</h1><button onClick={refreshCurrentTab} className="btn2">{loading ? "Đang tải..." : "Tải lại"}</button></div>{settings.announcement && <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mb-5 whitespace-pre-line">{settings.announcement}</div>}
    {tab === "services" && <section><div className="flex gap-3 flex-wrap mb-5"><input value={search} onChange={e => setSearch(e.target.value)} className="input flex-1 min-w-[240px] !mb-0" placeholder="Tìm dịch vụ..." /><select value={selectedCarrier} onChange={e => setSelectedCarrier(e.target.value)} className="input w-auto !mb-0">{carriers.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select></div>{!filteredServices.length && <p className="text-slate-500">Hiện chưa có dịch vụ nào được mở.</p>}<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{filteredServices.map(s => <div className="card" key={s.sourceKey || s.id}><h3 className="text-xl font-black">{s.name}</h3><p className="text-slate-500">{s.provider || "API"}</p>{s.note && <p className="text-sm mt-2 whitespace-pre-line">{s.note}</p>}<p className="text-2xl font-black mt-4">{money(s.price)}</p><button disabled={busy} onClick={() => rentNumber(s)} className="btn w-full mt-4">Thuê số</button></div>)}</div></section>}
    {tab === "orders" && <section className="space-y-4">{orders.map(o => <div className="card" key={o.id}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="text-xl font-black">{o.appName}</h3><p>Số: <b>{o.number}</b> | Giá: <b>{money(o.price)}</b></p><p>Trạng thái: <b>{o.status}</b> | {new Date(o.createdAt).toLocaleString("vi-VN")}</p>{o.sms && <p className="mt-2 whitespace-pre-line">SMS: {o.sms}</p>}{o.code && <p className="text-2xl font-black text-emerald-600 mt-2">OTP: {o.code}</p>}</div>{o.status === "waiting" && <div className="flex gap-2"><button onClick={() => checkCode(o)} className="btn2">Check OTP</button><button onClick={() => cancelOrder(o)} className="bg-rose-600 text-white rounded-xl px-4 py-2 font-bold">Hủy</button></div>}</div></div>)}{!orders.length && <p>Chưa có đơn nào.</p>}</section>}
    {tab === "topup" && <section className="grid md:grid-cols-2 gap-4"><div className="card"><h2 className="text-2xl font-black mb-3">Thông tin chuyển khoản</h2><p>Ngân hàng: <b>{settings.bankName}</b></p><p>Số tài khoản: <b>{settings.bankAccountNumber}</b></p><p>Chủ tài khoản: <b>{settings.bankBeneficiary}</b></p><p>Nội dung: <b>{user.username}</b></p>{settings.bankQrUrl && <img src={settings.bankQrUrl} className="max-w-xs mt-4 rounded-xl" />}<p className="whitespace-pre-line text-slate-600 mt-4">{settings.topupNote}</p></div><div className="card"><h2 className="text-2xl font-black mb-3">Tạo yêu cầu nạp</h2><input value={topupAmount} onChange={e => setTopupAmount(e.target.value)} className="input" placeholder="Số tiền đã chuyển" /><input value={topupNote} onChange={e => setTopupNote(e.target.value)} className="input" placeholder="Ghi chú / mã giao dịch" /><button onClick={createTopup} disabled={busy} className="btn w-full">Gửi yêu cầu</button></div><div className="md:col-span-2 card"><h2 className="text-2xl font-black mb-3">Lịch sử nạp</h2>{topups.map(t => <p key={t.id} className="border-b py-2">{money(t.amount)} - {t.status} - {new Date(t.createdAt).toLocaleString("vi-VN")}</p>)}</div></section>}
    {tab === "adminTopups" && isAdmin && <section className="space-y-4">{topups.map(t => <div className="card" key={t.id}><h3 className="font-black">{t.username} muốn nạp {money(t.amount)}</h3><p>Trạng thái: {t.status}</p>{t.note && <p>Ghi chú: {t.note}</p>}{t.status === "pending" && <div className="flex gap-2 mt-3"><button onClick={() => approveTopup(t)} className="bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold">Duyệt</button><button onClick={() => rejectTopup(t)} className="bg-rose-600 text-white rounded-xl px-4 py-2 font-bold">Từ chối</button></div>}</div>)}</section>}
    {tab === "users" && isAdmin && <section className="overflow-x-auto"><table className="w-full bg-white"><thead><tr className="text-left border-b"><th>User</th><th>Role</th><th>Đã nạp</th><th>Đã dùng</th><th>Còn lại</th><th>Hành động</th></tr></thead><tbody>{users.map(u => <tr key={u.id} className="border-b"><td className="py-3 font-bold">{u.username}</td><td>{u.role}</td><td>{money(u.totalTopup || 0)}</td><td>{money(u.totalUsed || 0)}</td><td>{money(u.balance)}</td><td className="space-x-2"><button onClick={() => adjustBalance(u)} className="btn2">Cộng/trừ</button><button onClick={() => changeUserPass(u)} className="bg-amber-500 text-white rounded-xl px-3 py-2 font-bold">Đổi pass</button><button onClick={() => deleteUser(u)} className="bg-rose-600 text-white rounded-xl px-3 py-2 font-bold">Xóa</button></td></tr>)}</tbody></table></section>}
    {tab === "adminServices" && isAdmin && <section><div className="flex gap-2 flex-wrap mb-4"><button onClick={() => loadAdminServices(true)} className="btn2">Tải dịch vụ API</button><button onClick={() => bulkSetHidden(true)} className="bg-rose-600 text-white rounded-xl px-4 py-2 font-bold">Ẩn tất cả</button><button onClick={() => bulkSetHidden(false, true)} className="bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold">Hiện dịch vụ đang tìm</button><button onClick={() => bulkSetHidden(true, true)} className="bg-amber-500 text-white rounded-xl px-4 py-2 font-bold">Ẩn dịch vụ đang tìm</button></div><input value={adminServiceSearch} onChange={e => setAdminServiceSearch(e.target.value)} className="input" placeholder="Tìm dịch vụ, ID hoặc nguồn..." /><p className="mb-4 text-slate-500">Tổng: {providerCounts.total || 0}, hiện: {providerCounts.visible || 0}, ẩn: {providerCounts.hidden || 0}</p><div className="space-y-3">{filteredAdminServices.map(s => <div className="card" key={s.sourceKey || s.id}><div className="grid md:grid-cols-[1fr_140px_120px_160px] gap-3 items-center"><div><b>{s.originalName}</b><p className="text-sm text-slate-500">{s.provider} | {s.sourceKey}</p></div><input defaultValue={s.price} onBlur={e => saveService(s, { price: Number(e.target.value) })} className="input !mb-0" /><button onClick={() => saveService(s, { hidden: !s.hidden })} className={s.hidden ? "bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold" : "bg-rose-600 text-white rounded-xl px-4 py-2 font-bold"}>{s.hidden ? "Bỏ ẩn" : "Ẩn"}</button><input defaultValue={s.name} onBlur={e => saveService(s, { name: e.target.value } as any)} className="input !mb-0" /></div></div>)}</div></section>}
    {tab === "api" && isAdmin && <section><div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mb-5">API key không hiển thị đầy đủ. Ô nào để trống thì giữ nguyên key cũ.</div><div className="grid md:grid-cols-2 gap-4"><div className="card"><h2 className="text-2xl font-black">chaycodeso3</h2><label className="block my-3"><input type="checkbox" checked={providerSettings.chayEnabled} onChange={e => setProviderSettings({ ...providerSettings, chayEnabled: e.target.checked })} /> Bật nguồn này</label><p>Key hiện tại: {providerSettings.chayApiKeyMasked || "Chưa cấu hình"}</p><input value={chayApiKey} onChange={e => setChayApiKey(e.target.value)} className="input mt-3" placeholder="Dán API key chaycodeso3 mới" /></div><div className="card"><h2 className="text-2xl font-black">CodeSim</h2><label className="block my-3"><input type="checkbox" checked={providerSettings.codesimEnabled} onChange={e => setProviderSettings({ ...providerSettings, codesimEnabled: e.target.checked })} /> Bật nguồn này</label><p>Key hiện tại: {providerSettings.codesimApiKeyMasked || "Chưa cấu hình"}</p><input value={codesimApiKey} onChange={e => setCodesimApiKey(e.target.value)} className="input mt-3" placeholder="Dán API key CodeSim mới" /></div></div><div className="mt-4 flex gap-3"><button onClick={saveProviderSettings} className="btn">Lưu cấu hình API</button><button onClick={testProvider} className="btn2">Test cả 2 API</button></div>{providerTest && <pre className="bg-slate-950 text-green-300 rounded-2xl p-4 mt-4 overflow-auto text-xs">{JSON.stringify(providerTest, null, 2)}</pre>}</section>}
    {tab === "settings" && isAdmin && <section className="grid md:grid-cols-2 gap-4"><input value={settings.siteName} onChange={e => setSettings({ ...settings, siteName: e.target.value })} className="input" placeholder="Tên web" /><input value={settings.logoText} onChange={e => setSettings({ ...settings, logoText: e.target.value })} className="input" placeholder="Logo text" /><input value={settings.bankName} onChange={e => setSettings({ ...settings, bankName: e.target.value })} className="input" placeholder="Ngân hàng" /><input value={settings.bankAccountNumber} onChange={e => setSettings({ ...settings, bankAccountNumber: e.target.value })} className="input" placeholder="Số tài khoản" /><input value={settings.bankBeneficiary} onChange={e => setSettings({ ...settings, bankBeneficiary: e.target.value })} className="input" placeholder="Chủ tài khoản" /><input value={settings.bankQrUrl} onChange={e => setSettings({ ...settings, bankQrUrl: e.target.value })} className="input" placeholder="Link QR" /><textarea value={settings.announcement} onChange={e => setSettings({ ...settings, announcement: e.target.value })} className="input md:col-span-2 min-h-[100px]" placeholder="Thông báo" /><textarea value={settings.topupNote} onChange={e => setSettings({ ...settings, topupNote: e.target.value })} className="input md:col-span-2 min-h-[100px]" placeholder="Ghi chú nạp tiền" /><button onClick={saveSettings} className="btn md:col-span-2">Lưu cài đặt</button></section>}
  </div></main></div></div>;
}
function Toast({ text }: { text: string }) { return <div className="fixed top-5 left-1/2 -translate-x-1/2 bg-slate-900 text-white rounded-2xl px-5 py-3 z-50 shadow-xl font-bold">{text}</div>; }
function Logo({ settings }: { settings: Settings }) { return settings.logoImage ? <img src={settings.logoImage} className="w-14 h-14 rounded-2xl object-cover" /> : <div className="w-14 h-14 rounded-2xl bg-indigo-600 text-white grid place-items-center font-black">{settings.logoText || "OTP"}</div>; }
